import arcade

SCREEN_WIDTH = 480
SCREEN_HEIGHT = 600
SCREEN_TITLE = 'Tetris Clone'
SCALING = 1.0

SIDE_MARGIN = 60
BOTTOM_MARGIN = 40

NEXT_QUEUE_HEIGHT = 72
NEXT_QUEUE_WIDTH = 120
NEXT_QUEUE_CX = 348
NEXT_QUEUE_CY = 420
NEXT_QUEUE_X_OFFSET = 312
NEXT_QUEUE_Y_OFFSET = 408

# Colors
WHITE = arcade.color.WHITE
WHITE_SMOKE = arcade.color.WHITE_SMOKE
DARK_GRAY = arcade.color.DARK_GRAY
BLACK = arcade.color.BLACK
YELLOW = arcade.color.YELLOW
LIGHT_BLUE = arcade.color.LIGHT_BLUE
PURPLE = arcade.color.PURPLE
ORANGE = arcade.color.ORANGE
DARK_BLUE = arcade.color.DARK_BLUE
GREEN = arcade.color.GREEN
RED = arcade.color.RED

COLORS = [None, None, YELLOW, LIGHT_BLUE,
          PURPLE, ORANGE, DARK_BLUE, GREEN, RED]
